### ISSUE TITLE
Focus URL input field when you open the app

### ISSUE THREAD

**Issue by jvdmeij** [kamranahmedse/pennywise#10]
By focussing the URL input field immediately, you can open PW and press cmd-v followed by enter. Saves you the step to focus the field yourself.

**Comment by The-Code-Monkey** [comment]
This or we could do it in the way that you highlight the url then rightclick and open pennywise from the menu and it will autofill the url and retrieve it

**Comment by kamranahmedse** [comment]
@akash-joshi sure, just trigger the focus in `componentDidMount` hook

**Comment by akash-joshi** [comment]
How do I deploy the built files ? I was just thinking of adding an autofocus tag to the input element.

**Comment by The-Code-Monkey** [comment]
The built should only be deployed by @kamranahmedse in my opinion @akash-joshi that way we keep the build done the same every time.

**Comment by akash-joshi** [comment]
@The-Code-Monkey I meant locally. Since running using yarn start triggers the dev console to be focussed first.

**Comment by The-Code-Monkey** [comment]
oh if you go into electron.js in public and remove the if dev open console statement it wont open the dev console

**Comment by The-Code-Monkey** [comment]
then restart the yarn start

**Comment by akash-joshi** [comment]
Thanks !

**Comment by The-Code-Monkey** [comment]
no worries happy to help

**Comment by shanmukhateja** [comment]
> @akash-joshi sure, just trigger the focus in `componentDidMount` hook

Why not add a `autofocus` HTML tag to the input field?

**Comment by akash-joshi** [comment]
Addressed in #18

**Comment by kamranahmedse** [comment]
@shanmukhateja [because it doesn't work all the time](https://davidwalsh.name/react-autofocus). But anyways, thanks @akash-joshi for the PR. I will push the build in a moment.
