### ISSUE TITLE
Feature Request: Pipe URL from the "open" command in the terminal

### ISSUE THREAD

**Issue by macgeekpro** [kamranahmedse/pennywise#111]
**Do you want to request a *feature* or report a *bug*?**

Feature

**What is the current behavior?**

No such behavior

**Expected behavior**

The ability to accept and open url piped from the open command in the terminal

**URL attempting to access**

n/a

**Screenshots (Optional But May Be Requested)**

n/a

**Pennywise Version:**
0.8.0

**OS / OS Version:**

OSX Mojave

Any issue that doesn't have all of these filled in will be closed, if yours is closed reopen with everything filled in.

**Comment by adamonsoon** [comment]
If you're using the latest version, this should work: `open /Applications/Pennywise.app --args --url "google.com"`

**Comment by macgeekpro** [comment]
@adamonsoon thanks for that great pointer.
