### ISSUE TITLE
Video unavailable

### ISSUE THREAD

**Issue by florindediu** [kamranahmedse/pennywise#116]
**Do you want to request a *feature* or report a *bug*?**
Report *bug*
**What is the current behavior?**
Some video are not displayed. Error: Video unavailable
**Expected behavior**
to work 
**URL attempting to access**
https://www.youtube.com/embed/playlist?autoplay=1&list=PLAaxNZrbfWIm36lcSV9JPrP3VTTZY7G_U
**Screenshots (Optional But May Be Requested)**
https://drive.google.com/open?id=19vCbkWDkn4_ydWjfeAU6XhmSVPuzQ18z
**Pennywise Version:**
0.80
**OS / OS Version:**
10.13.6
Any issue that doesn't have all of these filled in will be closed, if yours is closed reopen with everything filled in.

**Comment by kamranahmedse** [comment]
Permissions on some videos do not allow the embedding feature which is used by default while playing the videos. In that case, you may try by turning the "Edit > Embed" off

![image](https://user-images.githubusercontent.com/4921183/65388628-a536b100-dd5e-11e9-8157-7c88ad669b60.png)

Try the URL again without `/embed/` in the URL https://www.youtube.com/playlist?autoplay=1&list=PLAaxNZrbfWIm36lcSV9JPrP3VTTZY7G_U

**Comment by florindediu** [comment]
Thanks for reply. Is working now. 
Question: is there any app/plugin for block ads during youtube view? For MacOS.
On chrome browser i have an extension, but i want also on Pennywise to block the ads.
