### ISSUE TITLE
Feature Request: `file://` support

### ISSUE THREAD

**Issue by boxsnake** [kamranahmedse/pennywise#118]
Feature request:

Can I open a local file with `file://` protocol?
From my test, Pennywise does not support `file://` and any link will goes `http(s)` if no protocol given.

I am request if you can add `file://` protocol support, thanks.

**Comment by alxwrd** [comment]
hi @boxsnake. The `file://` protocol is currently supported for Pennywise.

![showing the use of the file protocol in pennywise](https://user-images.githubusercontent.com/13941027/66914635-22c4a880-f00f-11e9-92fe-a1e0f31d7bf1.png)

However, don't forget you will need three slashes `///` as the third slash means "root directory".
https://stackoverflow.com/a/40070752/7220776.

**Comment by kamranahmedse** [comment]
Thanks @alxwrd
