### ISSUE TITLE
Doesn't open anything, be more specific

### ISSUE THREAD

**Issue by aolko** [kamranahmedse/pennywise#15]
So, i want to open my steam games in a floating window and i can't do so, due to the fact that this app only opens web urls and/or media, **not anything**, be more specific.

**Comment by The-Code-Monkey** [comment]
It has never claimed to open anything except urls if you look at the docs.

**Comment by aolko** [comment]
producthunt pages says otherwise, no mention of urls

![](https://i.imgur.com/lyZjInL.png)

**Comment by The-Code-Monkey** [comment]
This is the aim to be able to do this eventually, and will be coming in the future to the project. This has only just started development and is in the early stages if you would like i will start to work out a way to do a functionality like this if it is possible to run another app inside of this one like that. Just so i know what OS are you running.

**Comment by aolko** [comment]
Windows 10 1809
also please optimize your app's ram consumption, file size and installation path (some people have small C: SSDs, y know)

**Comment by The-Code-Monkey** [comment]
App consumption ram wise would be the same as running a chromium instance, file size could be worked on a little bit i will see if anything can be done about that.

**Comment by aolko** [comment]
i think ram consumption shoud be minimum 50-100mb, not 300 (that's what you get for relying on electron)

**Comment by The-Code-Monkey** [comment]
Will hopefully make a pr tonight to allow other types of files to be opened and overlayed. 
Keep an eye here for the pr number

**Comment by kamranahmedse** [comment]
Yes we need to rephrase that. Thank you for opening the issue – will do that.
