### ISSUE TITLE
Add Console Developer Console

### ISSUE THREAD

**Issue by The-Code-Monkey** [kamranahmedse/pennywise#2]
I am a web dev, saw this on reddit and it works as far as i am clear but my only issue is the fact it doesn't have a developer console similar to chrome, nor does it work if I have my window set to fullscreen within my mac environment.

Developer console is the only real thing stopping me from using this. would it be possible though with the dev console to make it detached from other window so i could have it in a different place.

I will add bullet pointed issues as I find them.

- doesn't have localstorage.
- url doesn't update if webpage changes via a link, (might be a react issue as i dev in react)

**Comment by mubaidr** [comment]
Opening devTools separate to main window is possible, I might work on this one. 
Should support local storage out of the box. 
Probably bug in updating url

**Comment by The-Code-Monkey** [comment]
Also im trying to add the keyboard shortcuts for opacity right now.

**Comment by The-Code-Monkey** [comment]
Commit made for keyboard shortcuts pr done

**Comment by The-Code-Monkey** [comment]
LocalStorage Does work it was my web app that was wrong my bad
