### ISSUE TITLE
Custom/collapsible Menu-Bar for Windows

### ISSUE THREAD

**Issue by tomlazar** [kamranahmedse/pennywise#22]
The current menu bar on windows takes up a lot of space and is distracting from the content. I have seen that other electron apps have been able to create a custom bar that is much better at using the space provided. 

![image](https://user-images.githubusercontent.com/10578934/47825074-02d4a000-dd3e-11e8-8359-6e22bf07ec48.png)

**Comment by kamranahmedse** [comment]
Fixed in 0.4.0. Please do let us know if you face any issues. Thanks
