### ISSUE TITLE
Reader view for websites.

### ISSUE THREAD

**Issue by kleerkoat** [kamranahmedse/pennywise#23]
just a wish, kind of like reader view in safari.

**Comment by akash-joshi** [comment]
@kamranahmedse Does this fit your vision for the app ?

**Comment by jvdmeij** [comment]
Outline could be easily implemented. Prefix the current url with https://outline.com/

**Comment by kamranahmedse** [comment]
Thanks for opening the issue but we have no plans for adding that.
