### ISSUE TITLE
Applescript Support

### ISSUE THREAD

**Issue by kleerkoat** [kamranahmedse/pennywise#24]
I think it would be great to have apple script support.

**Comment by akash-joshi** [comment]
Issue too vague. What do you mean ?

**Comment by akash-joshi** [comment]
Pennywise does focus on input by default when started. I think you can create a custom flow for that in Alfred. Copy current tab -> open pennywise -> cmd+v and Enter.

**Comment by jvdmeij** [comment]
> Pennywise does focus on input by default when started. I think you can create a custom flow for that in Alfred. Copy current tab -> open pennywise -> cmd+v and Enter.

Here you go, use this workflow in Alfred. Use the trigger 'pw' and the current active tab from both Chrome (or Safari) will be opened in Pennywise.

[Open active tab in Pennywise URL.alfredworkflow.zip](https://github.com/kamranahmedse/pennywise/files/2539883/Open.active.tab.in.Pennywise.URL.alfredworkflow.zip)

**Comment by The-Code-Monkey** [comment]
I would say the issue is too vague as it doesn't say what the issue is and whether it's a bug or feature request.

**Comment by kamranahmedse** [comment]
Thanks for opening the issue. It isn't something that we have in the roadmap; but feel free to open a PR.
