### ISSUE TITLE
Command+L not working

### ISSUE THREAD

**Issue by hironorinakauchi** [kamranahmedse/pennywise#25]
It seems to me that command+L doesn't work on my laptop. Not sure if it's only my laptop, but other than that everything seems to be working properly. FYI, I have the latest version of Macbook Pro. Thank you.

**Comment by kamranahmedse** [comment]
Thank you for reporting. The build wasn't published yet. Deployed in [0.3.1](https://github.com/kamranahmedse/pennywise/releases/tag/v0.3.1)
