### ISSUE TITLE
TypeError: Cannot read property 'hide' of undefied

### ISSUE THREAD

**Issue by reini-1** [kamranahmedse/pennywise#26]
Hi!

I just installed `pennywise_0.3.1_amd64.deb` on a Ubuntu 18.04 laptop and got the following error message when try to start:

**A JavaScript error occurred in the main process**
Uncaught Exception:
TypeError: Cannot read property 'hide' of undefied
  at BrowserWindow.mainWindow.on(/opt/Pennywise/resources/app.asar/public/electron.js:32:14)
  at BrwoserWindow.emit (events.js:182:13)

Processes running:
```
USER       PID  PPID %CPU %MEM    VSZ   RSS PAGEIN TT       PSR S  NI  STARTED     TIME COMMAND
reini    15758  2338  5.8  0.7 1546080 121764    0 tty2       2 S   0 10:02:59 00:00:00 /opt/Pennywise/pennywise
reini    15762 15758  0.2  0.2 364980 39276      0 tty2       6 S   0 10:02:59 00:00:00 /opt/Pennywise/pennywise --type=zygote --no-sandbox
reini    15789 15758  1.5  0.6 661156 99008      0 tty2       4 S   0 10:02:59 00:00:00 /opt/Pennywise/pennywise --type=gpu-process --no-sandbox --gpu-preferences=KAAAAAAAAACAAACAAQAAAAAAAAAAAGAAEAAAAAAAAAAAAAAAAAAAAAgAAAAAAAAA --service-request-channel-token=53A80ED8E22283BF3D82026DEA669FF6
reini    15794 15762  3.0  0.5 1085304 96772     0 tty2       1 S   0 10:02:59 00:00:00 /opt/Pennywise/pennywise --type=renderer --no-sandbox --service-pipe-token=8419ABE7B337BF1212DBA47477A6CEEC --lang=en-US --app-path=/opt/Pennywise/resources/app.asar --node-integration=true --webview-tag=true --no-sandbox --background-color=#16171a --num-raster-threads=4 --enable-main-frame-before-activation --enable-compositor-image-animations --service-request-channel-token=8419ABE7B337BF1212DBA47477A6CEEC --renderer-client-id=4 --shared-files=v8_context_snapshot_data:100,v8_natives_data:101
```
What is the problem?
Is there a workaroud or fix available?

Thanks in advance.

Reini

**Comment by akash-joshi** [comment]
I believe this is because of ```app.dock.hide()``` in public/electron.js
Maybe different branch for Ubuntu, @kamranahmedse ?

**Comment by akash-joshi** [comment]
Fixed by these guys here : https://github.com/dtretyakov/teamcity-tray-notifier/issues/11.

I'll drop a PR

**Comment by kamranahmedse** [comment]
Fixed in https://github.com/kamranahmedse/pennywise/releases/tag/0.3.3
Thank you for reporting :)
