### ISSUE TITLE
Allow user to toggle title bar

### ISSUE THREAD

**Issue by mariuskiessling** [kamranahmedse/pennywise#28]
First of all: Thank you for starting this project. This has been a thing I needed for quite some time.

While using Pennywise, the title bar takes up quite some space and when watching full screen videos it is simply not needed. Thus I would like to suggest the option to toggle the title bar. The API needed for this feature is quite simple to implement (https://electronjs.org/docs/api/frameless-window).

![image](https://user-images.githubusercontent.com/9326374/47848713-88546080-ddcf-11e8-8f23-e86ba616e2f0.png)

It would also be possible to simply hide the operating system's title bar in all cases and set the draggable region to the nav bar. In this case the user could move the window when dragging the nav bar. On screens where no nav bar is present (like the welcome screen) the draggable region could be the whole interface because the option does not interfere with any component there.

If this feature is approved by the project's maintainer I would love to contribute a pull request.

**Comment by kamranahmedse** [comment]
Thanks @mariuskiessling. Yes it is something that we have in the roadmap. It wasn't included in the initial release because I am not sure about the cross-platform compatibility.

**Comment by mariuskiessling** [comment]
That's a good point. I can assure you that this approach would work nicely on MacOS (because the menu bar is displayed permanently). I just sent a build to a friend of mine to get feedback on Windows.
The only issue I see is that if we would completely remove the title bar by default we would have to substitute it with a custom one. Only this way users on Windows (and partially Linux) would be able to close, minimize etc. the window.
The other option, that would work cross platform and would use the operating system's native APIs is a toggle option. This way users would be able to restore the systems title bar using a short cut.

**Comment by The-Code-Monkey** [comment]
I think this issue can be closed due to V0.4.0

**Comment by mariuskiessling** [comment]
@The-Code-Monkey I don't think V0.4.0 resolves this request. V0.4.0 only collapses the menu bar on a few platforms. This however does not include the title bar.

**Comment by The-Code-Monkey** [comment]
Ah ok I think there is a keyboard shortcut for removing the URL bar and the settings button

**Comment by mariuskiessling** [comment]
@The-Code-Monkey The navigation bar you are referring is a different part of the UI. It is drawn as part of the electron app and is not provided by the operating system.

**Comment by The-Code-Monkey** [comment]
@kamranahmedse i think we can close this as this is something that will not translate across all platforms.

**Comment by mariuskiessling** [comment]
@The-Code-Monkey I strongly disagree. Please take a look at one of my previous comments. There are (to my knowledge) two ways to implement this feature with solid cross platform support.

**Comment by akash-joshi** [comment]
@mariuskiessling You mentioned in your original comment that if the maintainer approves you will post a PR. As Kamran approved it below you, you are welcome to try implementing this yourself.

**Comment by akash-joshi** [comment]
You can't set frame false after creating BrowserWindow. So unfortunately, this option isn't toggleable.

**Comment by The-Code-Monkey** [comment]
Ah I didn't think about the toggle able bit so yeah. This would in turn not be possible to toggle

**Comment by akash-joshi** [comment]
I think this issue is too old and without solution. So it should be closed.

**Comment by akash-joshi** [comment]
Also, frameless windows aren't draggable

**Comment by akash-joshi** [comment]
@kamranahmedse
