### ISSUE TITLE
Changing opacity has no effect on Ubuntu 18.04

### ISSUE THREAD

**Issue by vhfmag** [kamranahmedse/pennywise#30]
The latest release fixed the stay on top feature (#4), but it still doesn't change opacity.

Tested on Ubuntu 18.04 with [pennywise_0.3.2_amd64.deb](https://github.com/kamranahmedse/pennywise/releases/download/0.3.2/pennywise_0.3.2_amd64.deb)

**Comment by kamranahmedse** [comment]
This is the limitation from Electron; changing the opacity, unfortunately, is supported only in Windows and macOS. We need to disable the icons and menu items on the other OS and clarify that in the readme.

![image](https://user-images.githubusercontent.com/4921183/47869082-6be01480-de1f-11e8-8c7b-fcd3f10a87d0.png)
