### ISSUE TITLE
Opacity not changing Ubuntu 18.1

### ISSUE THREAD

**Issue by PaxPax** [kamranahmedse/pennywise#32]
On Ubuntu 18.1, the opacity bar will increase and decrease given the command, but the actual opacity of the application does not. I have the application installed as a debian file.

**Comment by kamranahmedse** [comment]
Changing opacity is only supported in Windows and MacOS because of the platform limitation. I have removed the options in other platforms and put a note in the readme.

Thanks for opening the issue.
