### ISSUE TITLE
Preset bug reports or feature request issue templates 

### ISSUE THREAD

**Issue by The-Code-Monkey** [kamranahmedse/pennywise#33]
I think we should have some pre defined issue templates seeing as it runs across 3 different os and we have different versions we can rule out issues quicker if we ask people for OS version penny-wise version and if its a feature or but request by the template its using?

**Comment by kamranahmedse** [comment]
Good idea. I have added the templates. Thanks.

**Comment by The-Code-Monkey** [comment]
Any issue from now on that are added that don't use the template, I think should be closed instantly
