### ISSUE TITLE
Track Progress -- Open local PDFs (Working now)

### ISSUE THREAD

**Issue by akash-joshi** [kamranahmedse/pennywise#34]
**Do you want to request a *feature* or report a *bug*?**
I'll just keep this issue open to track the work on opening local PDFs

**What is the current behavior?**
Can't open pdfs

**Expected behavior**
Should Open PDFs

**OS / OS Version:**
All

**Comment by akash-joshi** [comment]
@kamranahmedse Should this be implemented by using a JS library to display the PDF ?

**Comment by The-Code-Monkey** [comment]
Yeah I would say use the default chromium one

**Comment by akash-joshi** [comment]
Tried using file input via ```<input type="file">``` but as it returns fakepath, it can't be used

**Comment by akash-joshi** [comment]
@kamranahmedse Can you acknowledge this ?

**Comment by akash-joshi** [comment]
Things which need to be improved : Check for extension; this is useful when media support is added

**Comment by The-Code-Monkey** [comment]
The reason you get fake path is because JavaScript can't get access to filepaths you need to do new fileReader

**Comment by akash-joshi** [comment]
@The-Code-Monkey It's working now. Check out my fork

**Comment by The-Code-Monkey** [comment]
Ok will do.

**Comment by akash-joshi** [comment]
@The-Code-Monkey Now in #46

**Comment by The-Code-Monkey** [comment]
Im not sure how it works ive selected a file and its not clear what im supposed to do next?

**Comment by The-Code-Monkey** [comment]
Ive added some styles i will make a pr to your fork ive not modified any of the files except from adding some styles to make it not the default button.

**Comment by akash-joshi** [comment]
Wait

**Comment by akash-joshi** [comment]
I've removed that, check #47

**Comment by The-Code-Monkey** [comment]
I'm on twitter @exoticcollector

**Comment by The-Code-Monkey** [comment]
Ive got the loaded file console logging the base 64 for the file it just need to now be displayed onto the page but im unsure of how you have set the rest of it up.

**Comment by The-Code-Monkey** [comment]
I have pushed to my local master branch if you want to take a look at what i have done i cant do much more today

**Comment by akash-joshi** [comment]
From #47, you just have to go under file -> open, or press cmd or ctrl + O and select the pdf you want to open.

**Comment by The-Code-Monkey** [comment]
Ah ok
