### ISSUE TITLE
Evade mode

### ISSUE THREAD

**Issue by itschytoo** [kamranahmedse/pennywise#35]
This is a Feature Request.

Hey, pennywise is a great idea!

What about an optional "evade"-mode?
Whenever the mouse comes near to the floating window it will move "out of the way", e.g. to the other side of the screen. 
Optionally it will automatically return when the mouse leaves the area.
To select the window, some modifier key has to be held, e.g. while pressing control the window will not evade.

**Comment by The-Code-Monkey** [comment]
I think this is a good thing I would say it should be a toggle rather than a holdable key. Not sure if this is possible but will have a look

**Comment by kamranahmedse** [comment]
Thank you for opening the issue but this isn't something that we are planning to add. 

However in the [latest release](https://github.com/kamranahmedse/pennywise/releases/tag/0.5.0) I have added the "detached mode" enabling which will make pennywise non-interactive and all the mouse interactions will fall down to the window below it. You can use it with the low transparency to make the app not come in your way while you work.
