### ISSUE TITLE
Remove the clown picture - please

### ISSUE THREAD

**Issue by richardk2016** [kamranahmedse/pennywise#45]
I am massively afraid of clowns and would still like to use this software. This is not fun but a medical problem.  You certainly don't want to intentionally hurt or harm anyone.  Please replace the clown image with something harmless. A monochrome pictogram maybe. Something like that http://downloadicons.net/clown-logo-icon-27682

**Comment by The-Code-Monkey** [comment]
I will have a look at this for you but at the end of the day it is down to @kamranahmedse as its his program

**Comment by akash-joshi** [comment]
@richardk2016 I can build one without the clown for you. What OS are you using ?

**Comment by Kondax** [comment]
Distributing a version _without_ the clown sounds fine, but I don't think it should be removed from the application for everybody else.

**Comment by akash-joshi** [comment]
@richardk2016 I'm building without the clowns. Watch my repo : https://github.com/akash-joshi/pennywise-plus

**Comment by nervusdm** [comment]
No offense, but Internet is full of troll. I believe it's one of them.

**Comment by necroshadow0** [comment]
@akash-joshi 
Dude. He licensed it. And copyrighted it too.
License
MIT © Kamran Ahmed
 look at the read me

**Comment by The-Code-Monkey** [comment]
its mit meaning you can change and redistribute it as much as you want.

**Comment by richardk2016** [comment]
Thank you so much for your support. I'll install the offered alternative. I didn't want to offend anyone.
