### ISSUE TITLE
Overlay over fullscreen macOS

### ISSUE THREAD

**Issue by The-Code-Monkey** [kamranahmedse/pennywise#5]
this might be a way to get it to work over the top of fullscreen mac programs https://github.com/electron/electron/issues/10078#issuecomment-425690924

**Comment by kamranahmedse** [comment]
I experimented on this one but as far as I know electron doesn't allow showing it over the full screen windows. But anyways, will keep it open and will see if achievable.

**Comment by kamranahmedse** [comment]
This has been fixed in [0.3.1](https://github.com/kamranahmedse/pennywise/releases/tag/v0.3.1). Thank you.
