### ISSUE TITLE
Don't update url in NavBar when movement page

### ISSUE THREAD

**Issue by HyunmoAhn** [kamranahmedse/pennywise#51]
**Do you want to request a *feature* or report a *bug*?**
feature

**What is the current behavior?**
Url in NavBar is not updated when movement page like click the link.

**Expected behavior**
Url in NavBar will change when movement page.

Is this intended?

**Comment by The-Code-Monkey** [comment]
This is not intended, i am not sure how to do this if you know how feel free to add a pr if not i will take a  look at it.

**Comment by melanieseltzer** [comment]
I have been looking into it, PR incoming.
