### ISSUE TITLE
Contributor messaging

### ISSUE THREAD

**Issue by The-Code-Monkey** [kamranahmedse/pennywise#53]
**Do you want to request a *feature* or report a *bug*?**

Feature

**What is the current behavior?**

Non

**Expected behavior**

Message board, whether is it slack or if it is twitter group message for contributors to be able to talk

**Comment by akash-joshi** [comment]
@kamranahmedse The issues are getting polluted. Add me and @The-Code-Monkey as collabarators so we can help you with maintenance and issue management.

**Comment by kamranahmedse** [comment]
Thanks. I have [created the community on spectrum](https://spectrum.chat/pennywise).

**Comment by akash-joshi** [comment]
Got it 👍
