### ISSUE TITLE
unable to reattach

### ISSUE THREAD

**Issue by The-Code-Monkey** [kamranahmedse/pennywise#54]
**Do you want to request a *feature* or report a *bug*?**

Bug

**What is the current behavior?**

On Detaching you cannot reattach keyboard command or selecting from top menu

**Expected behavior**

should reattach

**Screenshots**

**Pennywise Version:**

0.5.1

**OS / OS Version:**

latest macos

**Comment by kamranahmedse** [comment]
It should be fixed in [0.6.0](https://github.com/kamranahmedse/pennywise#auto-embed-videos). Please re-open if you still face any issues. Plus, it would be great if you could submit a Gif/Video this time :)

**Comment by The-Code-Monkey** [comment]
yeah will do sorry
