### ISSUE TITLE
Use "anything" to describe what pennywise can open is inappropriate 

### ISSUE THREAD

**Issue by reorx** [kamranahmedse/pennywise#55]
**Do you want to request a *feature* or report a *bug*?**
Neither, a document suggestion.

**What is the current behavior?**
> Pennywise allows you to open anything in a small floating window that always stays on top of the other applications all the time

**Expected behavior**
> Pennywise allows you to open **url** in a small floating window that always stays on top of the other applications all the time

At the first sight, it makes me feel that pennywise is a tool that can turn anything (in the operating system) into a floating window. For example an application window, a image, a text file. But it can only float a website it opens. This is quite misleading IMAO…

**Comment by The-Code-Monkey** [comment]
With the latest version you are able to open files using a keyboard shortcut, this will be deployed soon watch for new releases

**Comment by kamranahmedse** [comment]
Agreed, we need to that. Will do it along the release tonight. Thanks!

**Comment by reorx** [comment]
@fbartels if this is a problem in code I'll do, but the author should have better expression, as long as the idea is the same.

@kamranahmedse I'm glad you accept it, cheers :)

**Comment by kamranahmedse** [comment]
Thanks guys, I have clarified that in the readme
