### ISSUE TITLE
PDF working on Windows

### ISSUE THREAD

**Issue by akash-joshi** [kamranahmedse/pennywise#56]
**Do you want to request a *feature* or report a *bug*?**
Feature

**What is the current behavior?**
I just tested my old PR related to opening PDFs in Pennywise and it worked without issue in Windows 7. You might want to consider adding that feature back

**OS / OS Version:**
Windows 7

**Comment by The-Code-Monkey** [comment]
Was this not merged I thought it was?

**Comment by akash-joshi** [comment]
@The-Code-Monkey We need a plugin to use the inbuilt chromium one in electron.

@kamranahmedse closed my PR as he thought that it would have issues in platforms other than Mac. Also, he doesn't want to maintain Pennywise as a PDF viewer.

You can check the current roadmap for the app's intent

**Comment by The-Code-Monkey** [comment]
thats fine but i thought it was supposed to open files?

**Comment by akash-joshi** [comment]
Yeah, now it isn't supposed to. Only websites

**Comment by The-Code-Monkey** [comment]
Well at the end of the day it's his repo up to him.

**Comment by akash-joshi** [comment]
I'm maintaining the file opening goal in my fork : https://github.com/akash-joshi/pennywise-plus

**Comment by The-Code-Monkey** [comment]
Check my version will allow you to open images, json and other files that chrome natively opens you just have to write it like file:///path/path/path

**Comment by The-Code-Monkey** [comment]
All i need to do is put the keyboard shortcut in to open it

**Comment by akash-joshi** [comment]
@The-Code-Monkey You can use my code for the keyboard shortcut. Come on Twitter

**Comment by kamranahmedse** [comment]
I am still planning on adding the open file support – it's just the PDF opening that I had wavering in my mind about; but that also, I am testing @akash-joshi's PR on any Linux distro today and if it works fine, I will pull it in. Thank you!

**Comment by The-Code-Monkey** [comment]
I am unable to do any more work until later today but i will use your shortcut and stuff @akash-joshi

**Comment by akash-joshi** [comment]
@The-Code-Monkey Your method works for everything except pdfs. So I guess we still need to use the plugin for pdfs

**Comment by The-Code-Monkey** [comment]
Does it work with the cmd + o

**Comment by akash-joshi** [comment]
Yes

**Comment by kamranahmedse** [comment]
Thank you. Will be deployed in the next release.
