### ISSUE TITLE
Bug: MacOS - errors for commands when the window is closed

### ISSUE THREAD

**Issue by steppefox** [kamranahmedse/pennywise#58]
### Do you want to request a *feature* or report a *bug*?

Bug

### What is the current behaviour?

Mac: When you close Pennywise window, it stays in launched Apps, but you can't open the window again and when you run short-commands or press menu buttons (View -> Toggle Navbar), you receive errors.

### Expected behavior

You can open Pennywise window again by pressing Cmd+N (Ctrl+N)
When you run short-commands or press menu buttons when the main window is closed - you don't see any errors

### Screenshots

![image](https://user-images.githubusercontent.com/4667275/47992914-7b48b180-e0ee-11e8-853f-e4dcf66bcf1a.png)

GIF:

![pennywise1](https://user-images.githubusercontent.com/4667275/47993064-db3f5800-e0ee-11e8-82f6-8616312948b1.gif)

### Pennywise Version:

0.5.1

### OS / OS Version:

macOS Mojave 10.14

**Comment by kamranahmedse** [comment]
Fixed. Will be deployed in 0.5.2. Thanks
