### ISSUE TITLE
Use mobile user-agent

### ISSUE THREAD

**Issue by geekdada** [kamranahmedse/pennywise#60]
**Do you want to request a *feature* or report a *bug*?**
feature

**What is the current behavior?**

**Expected behavior**

**Screenshots**

**Pennywise Version:**

**OS / OS Version:**

Why don't you use a mobile user-agent for better user experience, since the window got smaller?

**Comment by The-Code-Monkey** [comment]
Please fill in the full issue template please.

**Comment by kamranahmedse** [comment]
Duplicate of https://github.com/kamranahmedse/pennywise/issues/60
