### ISSUE TITLE
How about update for production builded app?

### ISSUE THREAD

**Issue by HyunmoAhn** [kamranahmedse/pennywise#67]
**Do you want to request a *feature* or report a *bug*?**
Do you think about update for builded app?
 
**What is the current behavior?**
I installed `pennywise` v0.5.1. Current latest version is `v0.6.0`. It is not updated.

**Expected behavior**
Update `pennywise` app from `v0.5.1` to `v0.6.0`.

**Comment by HyunmoAhn** [comment]
I know simple solution that implement update for builded app.

I will describe logic and code of simple solution.
If you like this, I want to make PR about this issue.

Using [electron-updater, show documentation if you want](https://www.electron.build/auto-update)
## Sequence
This method keeps your built applications up to date at all times.
1. When started application, app check if current version is latest version.
2. If current version is not latest, app install latest version **without asking user**.
3. App notify that complete of download about latest install file.
4. When app is quited, app is update latest version using install file.

### Precondition
- Need to uploaded builded file(like `pennywise-0.6.0.dmg`) in [github release page](https://github.com/kamranahmedse/pennywise/releases)
   - It doesn't matter because this is already being done. 
- This method use GitHub API. Therefore It exist limit for update check per hour. I think this limit is big enough for update but If you want huge service, this method may not be suitable for use.  
> The GitHub API currently has a rate limit of 5000 requests per user per hour. An update check uses up to 3 requests per check.

## Code
[Show my repository code](https://github.com/HyunmoAhn/Tiny-Timer/pull/8/files)
I made update for electron app. 

1. import `electron-updater`. 
```
import { autoUpdater } from 'electron-updater';
```
2. setting github repository config.
```
autoUpdater.setFeedURL({
  provider: 'github',
  owner: '{user-name}',
  protocol: 'https',
  repo: '{repo-name}',
});
```
3. call update check method (may be located when app is inited)
```
autoUpdater.checkForUpdatesAndNotify()
```

## Screen shot about notification.

![image](https://user-images.githubusercontent.com/23732795/47601413-2c728c00-da0b-11e8-9452-5e1d97e6864b.png)



Please comment your opinion.
If you like this method, I  can make PR.

**Comment by kamranahmedse** [comment]
Sure, [go ahead](https://www.electron.build/auto-update#quick-setup-guide) :)

**Comment by HyunmoAhn** [comment]
Close this issue because of completed by #68

**Comment by HyunmoAhn** [comment]
Close this issue because of completed by #68
