### ISSUE TITLE
Add option to hide nav-bar

### ISSUE THREAD

**Issue by DLvalentine** [kamranahmedse/pennywise#7]
For certain web pages and window resolutions, the nav-bar obstructs a lot of the screen real-estate. 

I'd like to propose a change that allows the toggling of the nav-bar, and perhaps shortcuts and auto-hiding features, as well. 

Just forked this (pretty awesome~) and might pin this as my first contribution

**Comment by DLvalentine** [comment]
I think it would also be useful to update the title bar to reflect the current address/file opened, since the nav-bar is better hidden.... and I know what app I have open ;)

**Comment by The-Code-Monkey** [comment]
I will look into this tonight when I am going to do a pr to update this, as I think a smaller/collapsed navbar could be beneficial

**Comment by DLvalentine** [comment]
Oh awesome! Sounds good. I'd be more than happy to contribute, if support is needed! 👍

**Comment by kamranahmedse** [comment]
Thanks guys
@The-Code-Monkey please hold on this one :) I have already started working on this.

**Comment by DLvalentine** [comment]
Sweet! Sounds good! I look forward to it! I've been looking for something like this for a while, great work!

**Comment by The-Code-Monkey** [comment]
No worries will hold off

**Comment by 0xsven** [comment]
Came here to request this. Maybe it could appear on hovering the window

**Comment by jvdmeij** [comment]
> Came here to request this. Maybe it could appear on hovering the window

I scrolled down to post this as well ;)

**Comment by kamranahmedse** [comment]
Thanks guys, this has been [resolved in v0.3.0](https://github.com/kamranahmedse/pennywise/releases/tag/0.3.0). You can use the shortcut <kbd>CommandOrCtrl + Shift + L</kbd> to toggle the top nav. @0xsven had a good idea but it was causing issues while dragging so I rather resorted to the shortcut. Let us know if there is any feedback.
