### ISSUE TITLE
Add to Brew Cask

### ISSUE THREAD

**Issue by zmarouf** [kamranahmedse/pennywise#73]
Super cool project!
I took the liberty of submitting a PR to Homebrew Cask for an easier installation experience on OSX.
https://github.com/Homebrew/homebrew-cask/pull/54636

Feel free to take over. If you're okay with it, I'll do a PR to update the README if/once merged.

**Comment by kamranahmedse** [comment]
Thank you. Sure, go ahead with the PR once it is merged :)
