### ISSUE TITLE
Spectrum chat link not available in read.me

### ISSUE THREAD

**Issue by akash-joshi** [kamranahmedse/pennywise#78]
**Do you want to request a *feature* or report a *bug*?**
Bug

**What is the current behavior?**
Spectrum discussion link not in the read.me

**Expected behavior**
It should be there

**URL attempting to access**
Spectrum URL of Pennywise

**Screenshots (Optional But May Be Requested)**

**Pennywise Version:**
----

**OS / OS Version:**
------

Any issue that doesn't have all of these filled in will be closed, if yours is closed reopen with everything filled in.

**Comment by kamranahmedse** [comment]
I removed it on purpose – I don't think there is any need for having multiple channels for communicating. GitHub issues are fine.

**Comment by akash-joshi** [comment]
Okay, good
