### ISSUE TITLE
Accessibility Options

### ISSUE THREAD

**Issue by DLvalentine** [kamranahmedse/pennywise#8]
It would be awesome if, since this is basically a chrome instance, we could control the web page's zoom level. 

Alternatively, when the window is smaller in size (like a mobile screen resolution), most web pages don't seem to detect that and switch over the mobile/smaller views. I am curious if that is something that could be adjusted somehow, and wonder if that is the fault of the application or the web page being navigated to. I tested it with popular sites like Twitch and Amazon.

**Comment by DLvalentine** [comment]
Just tested it with Github and it seemed to work. It's probably just a lack of a horizontal scroll bar that is breaking it for applications that only support down to an NxN small screen size.

**Comment by DLvalentine** [comment]
Moreover, other common functions like "Find" would be a nice to have.

**Comment by The-Code-Monkey** [comment]
The reason twitch and Amazon don't work is they use the JavaScript device tags to work out which website to load as m.twitch.com is different to twitch.com same with Amazon. It's just the way they built it

**Comment by The-Code-Monkey** [comment]
I will see if I can get find working tonight shouldn't be too hard look out for a pr linked here

**Comment by jvdmeij** [comment]
Cmd-L to focus the addressbar would be nice.

**Comment by The-Code-Monkey** [comment]
I did not look into this yet but I am off work today so I will work on it today. I will do CMD or ctrl f to find and CMD or ctrl l for the URL bar

**Comment by kamranahmedse** [comment]
Thank you for opening the issue but implementing "Find", "Zoom Level" etc is not in the scope of the application. I have added the <kbd>CommandOrCtrl + L</kbd> to focus the URL bar and <kbd>CommandOrCtrl + Shift + L</kbd> to toggle the top nav though.
