### ISSUE TITLE
Not working on my Ubuntu 14.04

### ISSUE THREAD

**Issue by Benoit-amo** [kamranahmedse/pennywise#80]
**Do you want to request a *feature* or report a *bug*?**
Bug !

**What is the current behavior?**
Does not launch

**Expected behavior**
Should work (is it ?)

**URL attempting to access**
No URL

**Screenshots (Optional But May Be Requested)**
```
$ ./pennywise-0.6.1-x86_64.AppImage 
5541 5535
/tmp/.mount_pennywO8MiJf/pennywise: /lib/x86_64-linux-gnu/libdbus-1.so.3: no version information available (required by /tmp/.mount_pennywO8MiJf/pennywise)
/tmp/.mount_pennywO8MiJf/pennywise: /lib/x86_64-linux-gnu/libdbus-1.so.3: no version information available (required by /tmp/.mount_pennywO8MiJf/pennywise)
Checking for update
Error: Error: Cannot find latest-linux.yml in the latest release artifacts (https://github.com/kamranahmedse/pennywise/releases/download/v0.6.1/latest-linux.yml): HttpError: 404 Not Found
"method: undefined url: https://github.com/kamranahmedse/pennywise/releases/download/v0.6.1/latest-linux.yml\n\nPlease double check that your authentication token is correct. Due to security reasons actual status maybe not reported, but 404.\n"
```

**Pennywise Version:**
0.6.1 AppImage

**OS / OS Version:**
Ubuntu 14.04 64bit

Any issue that doesn't have all of these filled in will be closed, if yours is closed reopen with everything filled in.

**Comment by kamranahmedse** [comment]
This should be fine now. Could you please retry opening it and see if it opens now?

**Comment by kamranahmedse** [comment]
Closing for no response – but it has been fixed. Please re-open the issue if it isn't resolved

**Comment by Benoit-amo** [comment]
It's resolved, thanks.
