### ISSUE TITLE
Brew install 404 error

### ISSUE THREAD

**Issue by nogorilla** [kamranahmedse/pennywise#81]
Installing via Brew on OsX fails with error: `Error: Download failed on Cask 'pennywise' with message: Download failed: https://github.com/kamranahmedse/pennywise/releases/download/0.6.1/Pennywise-0.6.1-mac.zip`

Issue:
Brew url is incorrect and should be: `https://github.com/kamranahmedse/pennywise/releases/download/v0.6.1/Pennywise-0.6.1-mac.zip`

**Comment by Pelirrojo** [comment]
Or even better v0.6.2 please :)
https://github.com/kamranahmedse/pennywise/releases/download/v0.6.2/Pennywise-0.6.2-mac.zip

**Comment by kamranahmedse** [comment]
This should be fine now. Please re-open if the issue persists. Thanks.
