### ISSUE TITLE
About Version (Wrong URL)

### ISSUE THREAD

**Issue by vivienney** [kamranahmedse/pennywise#85]
**Do you want to request a *feature* or report a *bug*?**
Bug

**What is the current behavior?**
The letter v is missing in the Help > About Version URL leading to Github's 404 page

Current URL: https://github.com/kamranahmedse/pennywise/releases/tag/0.6.2

**Expected behavior**
Correct URL: https://github.com/kamranahmedse/pennywise/releases/tag/v0.6.2

Add a v in the URL before the app version
 ```
         label: `About Version`,
          click() {
            shell.openExternal(`https://github.com/kamranahmedse/pennywise/releases/tag/${appVersion}`);
```
**URL attempting to access**
https://github.com/kamranahmedse/pennywise/releases/tag/v0.6.2

**Screenshots (Optional But May Be Requested)**

**Pennywise Version:**
0.6.2

**OS / OS Version:**
All

Any issue that doesn't have all of these filled in will be closed, if yours is closed reopen with everything filled in.

**Comment by HyunmoAhn** [comment]
It looks like typo error in release note.

Show below screenshot
![image](https://user-images.githubusercontent.com/23732795/48977571-4376cd80-f0e0-11e8-8216-d56f74a226d8.png)

Current version is `v0.6.2`. But previous version was released like `0.6.0` or `0.5.0`. 

If @kamranahmedse decide that add prefix `v` about new release version, need to edit URL according to suggestion in this Issue.
